import { tv } from "tailwind-variants";
import type { VariantProps } from "tailwind-variants";

/**
 * Defines the theme for a button component.
 */
export const buttonTheme = tv(
  {
    base: [
      "inline-flex",
      "items-center",
      "justify-center",
      "font-medium whitespace-nowrap",
      "focus-visible:ring-2",
      "focus-visible:ring-offset-2",
      "focus-visible:ring-components-focus-ring-focus-ring",
      "focus-visible:outline-none",
      "disabled:cursor-not-allowed",
    ],
    variants: {
      size: {
        md: ["gap-2", "py-3", "px-4", "rounded-lg", "text-base"],
        sm: ["gap-1", "py-2", "px-2", "rounded-md", "text-xs"],
      },
      fullWidth: {
        true: "w-full",
      },
      shape: {
        default: "",
        rounded: "rounded-full",
      },
      variant: {
        primary: [
          "text-components-buttons-primary-foreground",
          "border",
          "border-primary-700",
          "bg-components-buttons-primary-background",
          "hover:text-components-buttons-primary-foreground-hover",
          "hover:bg-components-buttons-primary-background-hover",
          "focus-visible:text-components-buttons-primary-foreground-focus",
          "focus-visible:bg-components-buttons-primary-background-focus",
          "disabled:text-components-buttons-primary-foreground-disabled",
          "disabled:bg-components-buttons-primary-background-disabled",
          "disabled:border-transparent",
        ],
        secondary: [
          "text-components-buttons-secondary-foreground",
          "border",
          "border-primary-500",
          "bg-components-buttons-secondary-background",
          "hover:text-components-buttons-secondary-foreground-hover",
          "hover:bg-components-buttons-secondary-background-hover",
          "focus-visible:text-components-buttons-secondary-foreground-focus",
          "focus-visible:bg-components-buttons-secondary-background-focus",
          "disabled:text-components-buttons-secondary-foreground-disabled",
          "disabled:bg-components-buttons-secondary-background-disabled ",
          "disabled:border-transparent",
        ],
        tertiary: [
          "text-components-buttons-tertiary-background",
          "border",
          "border-components-buttons-tertiary-background",
          "bg-transparent",
          "hover:text-components-buttons-tertiary-hover",
          "hover:border-components-buttons-tertiary-hover",
          "focus-visible:text-components-buttons-tertiary-focus",
          "focus-visible:border-components-buttons-tertiary-focus",
          "disabled:text-components-buttons-tertiary-disabled",
          "disabled:border-components-buttons-tertiary-disabled",
        ],
        "text-only": [
          "text-components-buttons-text-only-background",
          "border",
          "border-transparent",
          "bg-transparent",
          "hover:text-components-buttons-text-only-foreground-hover",
          "hover:bg-components-buttons-text-only-background-hover",
          "focus-visible:text-components-buttons-text-only-foreground-focus",
          "focus-visible:bg-components-buttons-text-only-background-focus",
          "disabled:text-components-buttons-tertiary-disabled",
          "disabled:bg-transparent",
        ],
        "low-emphasis": [
          "text-components-buttons-low-emphasis-foreground",
          "border",
          "border-transparent",
          "bg-components-buttons-low-emphasis-background",
          "hover:text-components-buttons-low-emphasis-foreground-hover",
          "hover:bg-components-buttons-low-emphasis-background-hover",
          "focus-visible:text-components-buttons-low-emphasis-foreground-focus",
          "focus-visible:bg-components-buttons-low-emphasis-background-focus",
          "disabled:text-components-buttons-low-emphasis-foreground-disabled",
          "disabled:bg-components-buttons-low-emphasis-background-disabled ",
        ],
        "low-emphasis-outlined": [
          "text-components-buttons-low-emphasis-outlined-foreground",
          "border",
          "border-components-buttons-low-emphasis-outlined-stroke",
          "bg-transparent",
          "hover:text-components-buttons-low-emphasis-outlined-foreground-hover",
          "hover:bg-components-buttons-low-emphasis-outlined-background-hover",
          "focus-visible:text-components-buttons-low-emphasis-outlined-foreground-hover",
          "focus-visible:bg-components-buttons-low-emphasis-outlined-background-hover",
          "disabled:text-components-buttons-low-emphasis-outlined-disabled",
          "disabled:border-components-buttons-low-emphasis-outlined-disabled",
          "hover:border-transparent focus-visible:border-transparent",
          "disabled:bg-transparent",
        ],
        alert: [
          "text-components-button-icon-alert-foreground",
          "border",
          "border-transparent",
          "bg-components-buttons-alert-background",
          "hover:text-components-buttons-alert-foreground-hover",
          "hover:bg-components-buttons-alert-background-hover",
          "focus-visible:text-components-buttons-alert-foreground-focus",
          "focus-visible:bg-components-buttons-alert-background-focus",
          "disabled:text-components-button-icon-alert-foreground-disabled",
          "disabled:bg-components-button-icon-alert-background-disabled",
        ],
        "icon-only": [
          "p-0 flex items-center justify-center",
          "text-components-button-icon-text-only-foreground",
          "border",
          "border-transparent",
          "bg-transparent",
          "hover:text-components-button-icon-text-only-foreground-hover",
          "hover:bg-components-button-icon-text-only-background-hover",
          "focus-visible:text-components-button-icon-low-emphasis-foreground-focus",
          "focus-visible:bg-components-button-icon-low-emphasis-background-focus",
          "disabled:text-components-button-icon-low-emphasis-outlined-foreground-disabled",
          "disabled:bg-transparent",
        ],
        tab: [
          "pb-2",
          "px-0",
          "border-b-[3px]",
          "border-transparent",
          "text-lg",
          "rounded-none",
          "lg:text-2xl",
          "text-neutral-400",
          "hover:border-primary-500",
          "hover:text-gray-800",
          "data-[active]:text-gray-800",
          "data-[active]:border-primary-500",
        ],
        unstyled: [],
      },
    },
    compoundVariants: [
      {
        size: "md",
        variant: "icon-only",
        class: ["h-11", "w-11", "rounded-lg"],
      },
      {
        size: "sm",
        variant: "icon-only",
        class: ["h-8", "w-8", "rounded-md"],
      },
    ],
    defaultVariants: {
      size: "md",
      variant: "primary",
      fullWidth: false,
    },
  },
  {
    responsiveVariants: true,
  },
);

/**
 * Represents the type of a button theme, which is derived from the `buttonTheme` variant props.
 */
export type ButtonTheme = VariantProps<typeof buttonTheme>;
